### PR TITLE
New website template

### PR DESCRIPTION
**Pull request by JosephThomasParker**
This is a version of the BOUT++ website put into a new Jekyll template.  The appearance is cleaner and more modern, and has nice responsive design features.  The content is unchanged, but some files have been shuffled around.  In particular, each markdown file has been moved from `<page>.markdown` to `<page>/index.md`

There are a couple of issues:

- The picture on the front page is a placeholder (and it's a copyrighted image that wasn't produced by BOUT...)
- The "Latest Post" is also a placeholder.
- The template has no bullet points, which looks strange in some places.  In particular the "What is BOUT++?" bullet list is a bit nonsensical. 
- The design encourages blog posts.  This would a nice feature, so long as we keep providing content for it; otherwise it can look badly out of date.
- The Jekyll template is MIT license, but isn't acknowledged anywhere on the website.  To some extent, this is the fault of the template!
- The github link points to the boutproject.github.io repo.  Should it point to BOUT/BOUT-dev instead?
- The website works locally on my computer. I think the only necessary change to make it work on github.io is to set the variable `localtest: false` in `_config.yml`.  I cannot check this though.  
- No satisfactory pun was found for the "about" section.  "about BOUT", "aBOUT", "aBOUT^2"?  They just don't work.

### CODE REVIEW

**Comment by bendudson** [comment]
Any preferred approach? There doesn't seem to be a good way to test this without pushing to the website. Perhaps merge this, then quickly fix up things which are broken, and remove copyrighted images?

**Comment by JosephThomasParker** [comment]
Most of the issues with the site itself can be fixed locally. Once that's in place, we can then merge and test that it works on github.io.

I think the two main things before we do this are:
+ Do we have a suitable background picture?  
+ Do we have text for a welcome post?

**Comment by bendudson** [comment]
Is the current background figure fig11b in images/ ? What are the restrictions on size?

**Comment by JosephThomasParker** [comment]
Yes, fig11b.png in assets/images.  To change it, set the variable `home_bgfile` in `_config.yml`, and running `jekyll server` will pick up the new image.  I think the image is resized to fit the width, so there isn't really a restriction on size.  Also, both jpg and png work; other file types might, but I haven't tried.

**Pull request merged**
