### PR TITLE
Workshop18

### PR DESCRIPTION
**Pull request by JosephThomasParker**
Add a page for Workshop 2018

### CODE REVIEW

**Comment by bshanahan** [comment]
Is 1 December too late for a registration deadline?  I would suggest early November.  (we could also have late registration)

**Comment by bendudson** [comment]
True; it would be good to know earlier, though the main constraint will be the dinner. How about 15th November?

**Comment by bshanahan** [comment]
sounds good to me.

**Comment by JosephThomasParker** [comment]
Thanks!

**Pull request merged**
